name: portworx
version: 1.0.40
description: A Helm chart for installing Portworx on Kubernetes.
tillerVersion: ">=2.7.2"
kubeVersion: ">=1.10.0"
appVersion: "2.12.2"
apiVersion: v1
keywords:
  - Storage
  - ICP
  - IKS
  - persistent disk
  - pvc
  - cloud native storage
  - persistent storage
  - portworx
  - amd64
  - Commercial
maintainers:
  - name: Vinayak Shinde
    email: vshinde@purestorage.com
  - name: Aditya Dani
    email: aditya@portworx.com
  - name: Tapas Sharma
    email: tapas@portworx.com
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png
